spring.application.name=backend
server.port=80


# 윈도우 - 오라클을 이용하여 데이터 베이스 연결
#spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@127.0.0.1:1521:xe
#spring.datasource.username=my_jarvis
#spring.datasource.password=1234

# 맥묵 -DBeaver를 사용하여 데이 베이트 연결
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=system
spring.datasource.password=1234

# MyBatis ì¤ì 
mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.type-aliases-package=kr.or.iei.*.model.dto
mybatis.configuration.jdbc-type-for-null=NULL

# JWT ì¤ì 
jwt.secret-key=kh.web.secret.code.gangnam.iclass
jwt.expire-minute=5
jwt.expire-hour-refresh=336